version: '3'
services:
  # Сервис для Spring Boot приложения
  spring-backend:
    build:
      context: ./app
    container_name: spring-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/db
      - SPRING_DATASOURCE_USERNAME=username
      - SPRING_DATASOURCE_PASSWORD=password
    depends_on:
      - postgres

  # Сервис для базы данных PostgreSQL
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password

  # Сервис для React приложения
  react-frontend:
    build:
      context: ./react-app
    container_name: react-frontend
    ports:
      - "3000:3000"
    depends_on:
      - spring-backend
